engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: eslint-config-standard
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- test/
